# Generated by Django 4.2.13 on 2024-10-01 23:39

import datetime
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBeneficio',
            fields=[
                ('beneficio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_beneficio', models.CharField(blank=True, max_length=60, null=True, verbose_name='Transportadora *')),
            ],
            options={
                'db_table': 'beneficio',
                'ordering': ['nome_beneficio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomBloco',
            fields=[
                ('bloco_id', models.AutoField(primary_key=True, serialize=False)),
                ('bloco', models.CharField(max_length=2, verbose_name='Bloco *')),
            ],
            options={
                'db_table': 'bloco',
                'ordering': ['bloco'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomCondominio',
            fields=[
                ('n_condominio', models.AutoField(primary_key=True, serialize=False, verbose_name='Número do Condomínio *')),
                ('nome_condominio', models.CharField(max_length=60, verbose_name='Nome do Condomínio *')),
            ],
            options={
                'db_table': 'condominio',
                'ordering': ['nome_condominio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomCondomino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_condomino', models.CharField(max_length=14, verbose_name='CPF Condômino *')),
                ('nome_condomino', models.CharField(max_length=40, verbose_name='Nome Condômino *')),
                ('data_nascimento_condomino', models.DateField(default='0000-00-00', verbose_name='Data Nascimento *')),
                ('telefone_condomino', models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='Telefone')),
                ('celular_condomino', models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular')),
                ('email_condomino', models.CharField(blank=True, default='-', max_length=40, null=True, verbose_name='E-mail')),
                ('data_aquisicao_imovel', models.DateField(default='0000-00-00', verbose_name='Data Aquisição Imóvel *')),
                ('n_condominio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio')),
            ],
            options={
                'db_table': 'condomino',
                'ordering': ['nome_condomino'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomEspaco',
            fields=[
                ('espaco_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_espaco', models.CharField(max_length=60, verbose_name='Nome espaço *')),
                ('dsc_espaco', models.CharField(blank=True, max_length=135, null=True, verbose_name='Descrição espaço *')),
                ('tempo_espaco', models.CharField(choices=[('1', '1'), ('24', '24')], default='1', max_length=3, verbose_name='Tempo de reserva')),
                ('valor_espaco', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor da locação *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número condomínio *')),
            ],
            options={
                'db_table': 'espaco',
                'ordering': ['nome_espaco'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomEspacoAdm',
            fields=[
                ('espaco_adm_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_espaco_adm', models.CharField(max_length=60, verbose_name='Nome espaço *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número condomínio *')),
            ],
            options={
                'db_table': 'espaco_adm',
                'ordering': ['nome_espaco_adm'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinanceiroEstrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Categoria')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='App_SGC.financeiroestrutura', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Estrutura do Financeiro',
                'verbose_name_plural': 'Estruturas do Financeiro',
                'db_table': 'financeiro_estrutura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('cpf_usuario', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(14)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['username'],
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_recebimento', models.DateField(verbose_name='Data de Recebimento')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Nº Documento')),
                ('tipo_documento', models.CharField(choices=[('NF', 'Nota Fiscal'), ('Recibo', 'Recibo'), ('Outros', 'Outros')], max_length=10, verbose_name='Tipo de Documento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor recebido *')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='App_SGC.financeiroestrutura', verbose_name='Categoria')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'db_table': 'receita',
                'ordering': ['data_vencimento'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PrevisaoReceitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_orcamento_receita', models.DateField(verbose_name='Data do Orçamento')),
                ('valor_orcamento_receita', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Orçamento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes_receita', to='App_SGC.financeiroestrutura', verbose_name='Categoria')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio')),
            ],
            options={
                'verbose_name': 'Previsão de Receita',
                'verbose_name_plural': 'Previsões de Receita',
                'db_table': 'previsao_receita',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PrevisaoDespesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_orcamento_despesa', models.CharField(help_text='Formato: MM-YYYY', max_length=7, verbose_name='Data do Orçamento')),
                ('valor_orcamento_despesa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Orçamento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes_despesa', to='App_SGC.financeiroestrutura', verbose_name='Categoria')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio')),
            ],
            options={
                'verbose_name': 'Previsão de Despesa',
                'verbose_name_plural': 'Previsões de Despesa',
                'db_table': 'previsao_despesa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomVeiculo',
            fields=[
                ('placa_veiculo', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Placa Veículo *')),
                ('marca_veiculo', models.CharField(max_length=30, verbose_name='Marca do Veículo *')),
                ('modelo_veiculo', models.CharField(max_length=30, verbose_name='Modelo do Veículo *')),
                ('cor_veiculo', models.CharField(max_length=30, verbose_name='Cor do Veículo *')),
                ('cpf_condomino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_por_cpf', to='App_SGC.customcondomino', verbose_name='CPF Condômino *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_condominio', to='App_SGC.customcondominio', verbose_name='Número do Condomínio')),
            ],
            options={
                'db_table': 'veiculo',
                'ordering': ['cpf_condomino'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUnidade',
            fields=[
                ('unidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('unidade', models.CharField(max_length=4, verbose_name='Unidade *')),
                ('bloco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_por_bloco', to='App_SGC.custombloco', verbose_name='Bloco *')),
                ('cpf_condomino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_por_cpf', to='App_SGC.customcondomino', verbose_name='CPF Condômino *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *')),
            ],
            options={
                'db_table': 'unidade',
                'ordering': ['bloco_id__bloco', 'unidade'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomTipoPatrimonio',
            fields=[
                ('tipo_patrimonio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_patrimonio', models.CharField(max_length=40, verbose_name='Nome patrimônio *')),
                ('n_patrimonio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número patrimônio')),
                ('cor_patrimonio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor patrimônio')),
                ('descricao_patrimonio', models.CharField(max_length=60, verbose_name='Descrição patrimônio *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número condomínio *')),
            ],
            options={
                'db_table': 'tipo_patrimonio',
                'ordering': ['nome_patrimonio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomReserva',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_reserva', models.CharField(max_length=14, verbose_name='CPF Reserva *')),
                ('data_reserva', models.DateField(default=datetime.date.today, verbose_name='Data reserva *')),
                ('hora_inicio_reserva', models.TimeField(verbose_name='Hora início reserva *')),
                ('espaco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_por_espaco', to='App_SGC.customespaco', verbose_name='Espaço *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número condomínio *')),
            ],
            options={
                'db_table': 'reserva',
                'ordering': ['data_reserva', 'hora_inicio_reserva'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomPets',
            fields=[
                ('pets_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pet', models.CharField(max_length=30, verbose_name='Nome pet *')),
                ('raca_pet', models.CharField(max_length=40, verbose_name='Raça pet *')),
                ('altura_pet', models.CharField(max_length=3, verbose_name='Altura pet *')),
                ('peso_pet', models.CharField(max_length=2, verbose_name='Peso pet *')),
                ('cpf_condomino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_por_cpf', to='App_SGC.customcondomino', verbose_name='CPF Condômino *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *')),
            ],
            options={
                'db_table': 'pets',
                'ordering': ['nome_pet'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomPatrimonio',
            fields=[
                ('patrimonio_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_patrimonio', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do patrimônio *')),
                ('Qtd_patrimonio', models.IntegerField(verbose_name='Qtd Patrimônio')),
                ('data_disposicao_patrimonio', models.DateField(verbose_name='Data disposição *')),
                ('data_baixa_patrimonio', models.DateField(blank=True, null=True, verbose_name='Data baixa *')),
                ('espaco_adm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_por_espaco', to='App_SGC.customespacoadm', verbose_name='Patrimônio *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *')),
                ('tipo_patrimonio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_por_tipo', to='App_SGC.customtipopatrimonio', verbose_name='Tipo patrimônio *')),
            ],
            options={
                'db_table': 'patrimonio',
                'ordering': ['tipo_patrimonio_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomOcorrencia',
            fields=[
                ('ocorrencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_ocorrencia', models.DateField(verbose_name='Data mudança *')),
                ('hora_ocorrencia', models.TimeField(verbose_name='Hora mudança *')),
                ('dsc_ocorrencia', models.CharField(blank=True, max_length=60, null=True, verbose_name='Transportadora *')),
                ('documento_ocorrencia', models.FileField(upload_to='documentos_ocorrencias/')),
                ('cpf_condomino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_por_cpf', to='App_SGC.customcondomino', verbose_name='CPF Condômino *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
            ],
            options={
                'db_table': 'ocorrencia',
                'ordering': ['data_ocorrencia', 'hora_ocorrencia'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomMudanca',
            fields=[
                ('mudanca_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_mudanca', models.DateField(verbose_name='Data mudança *')),
                ('hora_mudanca', models.TimeField(verbose_name='Hora mudança *')),
                ('transportadora', models.CharField(blank=True, max_length=40, null=True, verbose_name='Transportadora *')),
                ('placa_veiculo_transportadora', models.CharField(blank=True, max_length=7, null=True, verbose_name='Placa Veículo *')),
                ('bloco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudanca_por_bloco', to='App_SGC.custombloco', verbose_name='Bloco *')),
                ('cpf_condomino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudanca_por_cpf', to='App_SGC.customcondomino', verbose_name='CPF Condômino *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
                ('unidade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mudanca_por_unidade', to='App_SGC.customunidade', verbose_name='Mudança *')),
            ],
            options={
                'db_table': 'mudanca',
                'ordering': ['bloco_id__bloco', 'data_mudanca'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomGaragem',
            fields=[
                ('garagem_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_garagem', models.CharField(max_length=4, verbose_name='Garagem *')),
                ('bloco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_por_bloco', to='App_SGC.custombloco', verbose_name='Bloco *')),
                ('cpf_condomino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_por_cpf', to='App_SGC.customcondomino', verbose_name='CPF Condômino *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *')),
            ],
            options={
                'db_table': 'garagem',
                'ordering': ['bloco_id__bloco', 'n_garagem'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomCorrespondencia',
            fields=[
                ('correspondencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_recebimento_correspondencia', models.DateField(verbose_name='Data recebiemento *')),
                ('dsc_correspondencia', models.CharField(blank=True, max_length=60, null=True, verbose_name='Dsc *')),
                ('data_retirada_correspondencia', models.DateField(blank=True, null=True, verbose_name='Data retirada *')),
                ('retirante_correspondencia', models.CharField(blank=True, max_length=60, null=True, verbose_name='Retirante *')),
                ('bloco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondencia_por_bloco', to='App_SGC.custombloco', verbose_name='Bloco *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
                ('unidade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondencia_por_unidade', to='App_SGC.customunidade', verbose_name='Mudança *')),
            ],
            options={
                'db_table': 'correspondencia',
                'ordering': ['bloco_id__bloco', 'unidade_id__unidade'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomColaborador',
            fields=[
                ('cpf_colaborador', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF Condômino *')),
                ('nome_colaborador', models.CharField(max_length=40, verbose_name='Nome Colaborador *')),
                ('data_nascimento_colaborador', models.DateField(verbose_name='Data nascimento *')),
                ('endereco_colaborador', models.CharField(max_length=70, verbose_name='Endereço *')),
                ('telefone_colaborador', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefone')),
                ('celular_colaborador', models.CharField(max_length=11, verbose_name='Celular')),
                ('email_colaborador', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('nome_contato_colaborador', models.CharField(max_length=40, verbose_name='Nome Contato *')),
                ('celular_contato_colaborador', models.CharField(max_length=11, verbose_name='Celular Contato')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *')),
            ],
            options={
                'db_table': 'colaborador',
                'ordering': ['nome_colaborador'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='custombloco',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *'),
        ),
        migrations.CreateModel(
            name='CustomBeneficioRecebido',
            fields=[
                ('beneficio_recebido_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.custombeneficio', verbose_name='Benefício *')),
                ('cpf_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficio_recebido_por_colaborador', to='App_SGC.customcolaborador', verbose_name='CPF Colaborador *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
            ],
            options={
                'db_table': 'beneficio_recebido',
                'ordering': ['cpf_colaborador', 'beneficio_id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='custombeneficio',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *'),
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('caixa_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Caixa')),
                ('data_caixa', models.DateField(verbose_name='Data do Caixa')),
                ('historico_caixa', models.CharField(max_length=40, verbose_name='Histórico do Caixa')),
                ('valor_caixa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Caixa')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
            ],
            options={
                'db_table': 'caixa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('banco_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID do Banco')),
                ('data_banco', models.DateField(verbose_name='Data do Banco')),
                ('historico_banco', models.CharField(max_length=40, verbose_name='Histórico do Banco')),
                ('valor_banco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Banco')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
            ],
            options={
                'db_table': 'banco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor *')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor recebido *')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data pagamento *')),
                ('data_vencimento', models.DateField(default=datetime.date.today, verbose_name='Data vencimento *')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Nº documento *')),
                ('tipo_documento', models.CharField(choices=[('NF', 'NF'), ('Recibo', 'Recibo'), ('outros', 'Outros')], default='NF', max_length=6, verbose_name='Tipo do Documento')),
                ('descricao', models.CharField(blank=True, max_length=60, null=True, verbose_name='Dsc *')),
                ('documento', models.FileField(upload_to='documentos_ocorrencias/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to='App_SGC.financeiroestrutura', verbose_name='Categoria')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
            ],
            options={
                'db_table': 'conta_pagar',
                'ordering': ['data_vencimento', 'tipo_documento', 'categoria'],
                'managed': True,
                'unique_together': {('data_pagamento', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='CustomMorador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_morador', models.CharField(max_length=14, verbose_name='CPF Morador *')),
                ('nome_morador', models.CharField(max_length=40, verbose_name='Nome Morador *')),
                ('data_nascimento_morador', models.DateField(verbose_name='Data de Nascimento *')),
                ('parentesco_condomino', models.CharField(choices=[('Esposo', 'Esposo'), ('Esposa', 'Esposa'), ('Filho', 'Filho'), ('Filha', 'Filha'), ('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Locatário', 'Locatário'), ('Outros', 'Outros')], default='Outros', max_length=11, verbose_name='Parentesco')),
                ('celular_morador', models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular')),
                ('email_morador', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('cpf_condomino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradores_por_cpf', to='App_SGC.customcondomino', verbose_name='CPF Condômino *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numero_condominio', to='App_SGC.customcondominio', verbose_name='Número do Condomínio')),
            ],
            options={
                'db_table': 'morador',
                'ordering': ['nome_morador'],
                'managed': True,
                'unique_together': {('cpf_condomino', 'cpf_morador', 'n_condominio')},
            },
        ),
        migrations.AddConstraint(
            model_name='customcondomino',
            constraint=models.UniqueConstraint(fields=('cpf_condomino', 'n_condominio'), name='unique_condomino_condominio'),
        ),
        migrations.AlterUniqueTogether(
            name='customcondomino',
            unique_together={('cpf_condomino', 'n_condominio')},
        ),
        migrations.AlterUniqueTogether(
            name='custombeneficiorecebido',
            unique_together={('beneficio_id', 'cpf_colaborador', 'n_condominio')},
        ),
    ]
