# Generated by Django 5.0.4 on 2024-06-19 16:21

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomColaborador',
            fields=[
                ('cpf_colaborador', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='CPF Colaborador *')),
                ('nome_colaborador', models.CharField(max_length=40, verbose_name='Nome Colaborador *')),
                ('data_nascimento_colaborador', models.DateField(verbose_name='Data nascimento *')),
                ('endereco_colaborador', models.CharField(max_length=70, verbose_name='Endereço *')),
                ('telefone_colaborador', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefone')),
                ('celular_colaborador', models.CharField(max_length=11, verbose_name='Celular')),
                ('email_colaborador', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('nome_contato_colaborador', models.CharField(max_length=40, verbose_name='Nome Contato *')),
                ('celular_contato_colaborador', models.CharField(max_length=11, verbose_name='Celular Contato')),
            ],
            options={
                'db_table': 'colaborador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomCondominio',
            fields=[
                ('n_condominio', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Número do Condomínio *')),
                ('nome_condominio', models.CharField(max_length=60, verbose_name='Nome do Condomínio *')),
            ],
            options={
                'db_table': 'condominio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomCondomino',
            fields=[
                ('cpf_condomino', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='CPF Condômino *')),
                ('nome_condomino', models.CharField(max_length=40, verbose_name='Nome Condômino *')),
                ('data_nascimento_condomino', models.DateField(default='0000-00-00', verbose_name='Data Nascimento *')),
                ('bloco', models.CharField(max_length=2, verbose_name='Bloco *')),
                ('apartamento', models.CharField(max_length=4, verbose_name='Apartamento *')),
                ('telefone_condomino', models.CharField(blank=True, default='-', max_length=9, null=True, verbose_name='Telefone')),
                ('celular_condomino', models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular')),
                ('email_condomino', models.CharField(blank=True, default='-', max_length=40, null=True, verbose_name='E-mail')),
                ('data_aquisicao_imovel', models.DateField(default='0000-00-00', verbose_name='Data Aquisição Imóvel *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *')),
            ],
            options={
                'db_table': 'condomino',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomMorador',
            fields=[
                ('cpf_morador', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='CPF Morador *')),
                ('nome_morador', models.CharField(max_length=40, verbose_name='Nome Morador *')),
                ('data_nascimento_morador', models.DateField(verbose_name='Data de Nascimento *')),
                ('celular_morador', models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular')),
                ('email_morador', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('cpf_condomino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='CPF Condômino *')),
            ],
            options={
                'db_table': 'morador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('cpf_usuario', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(14)])),
                ('nivel', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('n_condominio', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
