# Generated by Django 4.2 on 2024-04-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condomino',
            fields=[
                ('cpf_condomino', models.IntegerField(primary_key=True, serialize=False, verbose_name='CPF Condômino *')),
                ('nome_condomino', models.CharField(max_length=40, verbose_name='Nome Condômino *')),
                ('bloco', models.CharField(max_length=2, verbose_name='Bloco *')),
                ('apartamento', models.CharField(max_length=4, verbose_name='Apartamento *')),
                ('telefone', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('data_aquisicao_imovel', models.DateField(verbose_name='Data aquisição imóvel *')),
                ('Condominio_numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('cpf_usuario', models.IntegerField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, max_length=2, null=True)),
                ('condominio_numero', models.IntegerField()),
            ],
        ),
    ]
