# Generated by Django 5.0.3 on 2024-07-02 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombloco',
            name='n_condominio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *'),
        ),
        migrations.CreateModel(
            name='CustomUnidade',
            fields=[
                ('unidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('unidade', models.CharField(max_length=4, verbose_name='Unidade *')),
                ('bloco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_por_bloco', to='App_SGC.custombloco', verbose_name='Bloco *')),
                ('cpf_condomino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidade_por_cpf', to='App_SGC.customcondomino', verbose_name='CPF Condômino *')),
                ('n_condominio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *')),
            ],
            options={
                'db_table': 'unidade',
                'ordering': ['bloco_id__bloco', 'unidade'],
                'managed': True,
            },
        ),
    ]
