# Generated by Django 5.0.4 on 2024-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommorador',
            name='parentesco_condomino',
            field=models.CharField(default='Outros', max_length=11, verbose_name='Parentesco'),
        ),
    ]
