# Generated by Django 5.0.3 on 2024-07-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommudanca',
            name='Teste',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Trans *'),
        ),
    ]
