# Generated by Django 5.0.3 on 2024-08-15 02:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompatrimonio',
            options={'managed': True, 'ordering': ['tipo_patrimonio_id']},
        ),
        migrations.CreateModel(
            name='CustomEspaco',
            fields=[
                ('espaco_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_espaco', models.CharField(max_length=60, verbose_name='Nome espaço *')),
                ('dsc_espaco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição espaço *')),
                ('tempo_espaco', models.CharField(choices=[('0', '0'), ('1', '1'), ('24', '24')], default='1', max_length=3, verbose_name='Tempo de reserva')),
                ('valor_espaco', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor da locação *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número condomínio *')),
            ],
            options={
                'db_table': 'espaco',
                'ordering': ['nome_espaco'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomReserva',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_reserva', models.DateField(default=datetime.date.today, verbose_name='Data reserva *')),
                ('hora_inicio_reserva', models.TimeField(verbose_name='Hora início reserva *')),
                ('cpf_morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.custommorador', verbose_name='CPF Morador *')),
                ('espaco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_por_espaco', to='App_SGC.customespaco', verbose_name='Espaço *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número condomínio *')),
            ],
            options={
                'db_table': 'reserva',
                'ordering': ['data_reserva', 'hora_inicio_reserva'],
                'managed': True,
            },
        ),
    ]
