# Generated by Django 5.0.3 on 2024-08-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcorrespondencia',
            name='data_retirada_correspondencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data retirada *'),
        ),
        migrations.AlterField(
            model_name='customcorrespondencia',
            name='retirante_correspondencia',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Retirante *'),
        ),
    ]
