# Generated by Django 4.2.13 on 2024-08-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='banco',
            table='banco',
        ),
    ]
