# Generated by Django 4.2.13 on 2024-08-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCorrespondencia',
            fields=[
                ('correspondencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_recebimento_correspondencia', models.DateField(verbose_name='Data recebiemento *')),
                ('dsc_correspondencia', models.CharField(blank=True, max_length=60, null=True, verbose_name='Dsc *')),
                ('data_retirada_correspondencia', models.DateField(blank=True, null=True, verbose_name='Data retirada *')),
                ('retirante_correspondencia', models.CharField(blank=True, max_length=60, null=True, verbose_name='Retirante *')),
                ('bloco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondencia_por_bloco', to='App_SGC.custombloco', verbose_name='Bloco *')),
            ],
            options={
                'db_table': 'correspondencia',
                'ordering': ['bloco_id__bloco', 'unidade_id__unidade'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomEspacoAdm',
            fields=[
                ('espaco_adm_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_espaco_adm', models.CharField(max_length=60, verbose_name='Nome espaço *')),
            ],
            options={
                'db_table': 'espaco_adm',
                'ordering': ['nome_espaco_adm'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomPatrimonio',
            fields=[
                ('patrimonio_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_patrimonio', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do patrimônio *')),
                ('data_disposicao_patrimonio', models.DateField(verbose_name='Data disposição *')),
                ('data_baixa_patrimonio', models.DateField(blank=True, null=True, verbose_name='Data baixa *')),
                ('espaco_adm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_por_espaco', to='App_SGC.customespacoadm', verbose_name='Patrimônio *')),
            ],
            options={
                'db_table': 'patrimonio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomTipoPatrimonio',
            fields=[
                ('tipo_patrimonio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_patrimonio', models.CharField(max_length=40, verbose_name='Nome patrimônio *')),
                ('n_patrimonio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número patrimônio')),
                ('cor_patrimonio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor patrimônio')),
                ('descricao_patrimonio', models.CharField(max_length=60, verbose_name='Descrição patrimônio *')),
            ],
            options={
                'db_table': 'tipo_patrimonio',
                'ordering': ['nome_patrimonio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinanceiroEstrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Estrutura do Financeiro',
                'verbose_name_plural': 'Estruturas do Financeiro',
                'db_table': 'financeiro_estrutura',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_recebimento', models.DateField(verbose_name='Data de Recebimento')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Nº Documento')),
                ('tipo_documento', models.CharField(choices=[('NF', 'Nota Fiscal'), ('Recibo', 'Recibo'), ('Outros', 'Outros')], max_length=10, verbose_name='Tipo de Documento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='App_SGC.financeiroestrutura', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'db_table': 'receita',
                'ordering': ['data_vencimento'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='customconta_receber',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customconta_receber',
            name='n_condominio',
        ),
        migrations.RemoveField(
            model_name='customconta_receber',
            name='nivel_1',
        ),
        migrations.RemoveField(
            model_name='customconta_receber',
            name='nivel_2',
        ),
        migrations.RemoveField(
            model_name='customconta_receber',
            name='nivel_3',
        ),
        migrations.RemoveField(
            model_name='customconta_receber',
            name='nivel_4',
        ),
        migrations.AlterUniqueTogether(
            name='customplano_conta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customplano_conta',
            name='n_condominio',
        ),
        migrations.AlterModelOptions(
            name='customcolaborador',
            options={'managed': True, 'ordering': ['nome_colaborador']},
        ),
        migrations.AlterModelOptions(
            name='customcondominio',
            options={'managed': True, 'ordering': ['nome_condominio']},
        ),
        migrations.AlterModelOptions(
            name='customcondomino',
            options={'managed': True, 'ordering': ['nome_condomino']},
        ),
        migrations.AlterModelOptions(
            name='custommorador',
            options={'managed': True, 'ordering': ['nome_morador']},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': True, 'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='customveiculo',
            options={'managed': True, 'ordering': ['cpf_condomino']},
        ),
        migrations.AlterField(
            model_name='custommorador',
            name='parentesco_condomino',
            field=models.CharField(choices=[('esposo', 'Esposo(a)'), ('filho', 'Filho(a)'), ('pai', 'Pai'), ('mae', 'Mãe'), ('locatario', 'Locatário'), ('outros', 'Outros')], default='outros', max_length=11, verbose_name='Parentesco'),
        ),
        migrations.AlterUniqueTogether(
            name='custombeneficiorecebido',
            unique_together={('beneficio_id', 'cpf_colaborador', 'n_condominio')},
        ),
        migrations.AlterUniqueTogether(
            name='custommorador',
            unique_together={('cpf_condomino', 'cpf_morador')},
        ),
        migrations.AlterModelTable(
            name='custommorador',
            table='morador',
        ),
        migrations.DeleteModel(
            name='CustomConta_Pagar',
        ),
        migrations.DeleteModel(
            name='CustomConta_Receber',
        ),
        migrations.DeleteModel(
            name='CustomPlano_Conta',
        ),
        migrations.AddField(
            model_name='receita',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio'),
        ),
        migrations.AddField(
            model_name='financeiroestrutura',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio'),
        ),
        migrations.AddField(
            model_name='financeiroestrutura',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='App_SGC.financeiroestrutura', verbose_name='Categoria Pai'),
        ),
        migrations.AddField(
            model_name='customtipopatrimonio',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número condomínio *'),
        ),
        migrations.AddField(
            model_name='custompatrimonio',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *'),
        ),
        migrations.AddField(
            model_name='custompatrimonio',
            name='tipo_patrimonio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_por_tipo', to='App_SGC.customtipopatrimonio', verbose_name='Tipo patrimônio *'),
        ),
        migrations.AddField(
            model_name='customespacoadm',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número condomínio *'),
        ),
        migrations.AddField(
            model_name='customcorrespondencia',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *'),
        ),
        migrations.AddField(
            model_name='customcorrespondencia',
            name='unidade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondencia_por_unidade', to='App_SGC.customunidade', verbose_name='Mudança *'),
        ),
    ]
