# Generated by Django 4.2.13 on 2024-08-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customplano_conta',
            name='nivel_4',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Nível 4 *'),
        ),
    ]
