# Generated by Django 5.0.4 on 2024-04-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condomino',
            name='Condominio_numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='condominio_numero',
            field=models.IntegerField(),
        ),
    ]
