# Generated by Django 5.0.3 on 2024-08-07 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0002_alter_customcorrespondencia_data_retirada_correspondencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customconta_pagar',
            name='valor_conta_paga',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor recebido *'),
        ),
        migrations.AddField(
            model_name='customconta_receber',
            name='valor_conta_recebimento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor recebido *'),
        ),
        migrations.AlterField(
            model_name='customconta_receber',
            name='valor_conta_receber',
            field=models.IntegerField(verbose_name='Valor a receber*'),
        ),
        migrations.CreateModel(
            name='CustomEspacoAdm',
            fields=[
                ('espaco_adm_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_espaco_adm', models.CharField(max_length=60, verbose_name='Nome espaço *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número condomínio *')),
            ],
            options={
                'db_table': 'espaco_adm',
                'ordering': ['nome_espaco_adm'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomTipoPatrimonio',
            fields=[
                ('tipo_patrimonio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_patrimonio', models.CharField(max_length=40, verbose_name='Nome patrimônio *')),
                ('n_patrimonio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número patrimônio')),
                ('cor_patrimonio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cor patrimônio')),
                ('descricao_patrimonio', models.CharField(max_length=60, verbose_name='Descrição patrimônio *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número condomínio *')),
            ],
            options={
                'db_table': 'tipo_patrimonio',
                'ordering': ['nome_patrimonio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomPatrimonio',
            fields=[
                ('patrimonio_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_disposicao_patrimonio', models.DateField(verbose_name='Data disposição *')),
                ('data_baixa_patrimonio', models.DateField(verbose_name='Data baixa *')),
                ('espaco_adm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_por_espaco', to='App_SGC.customespacoadm', verbose_name='Patrimônio *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *')),
                ('tipo_patrimonio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonio_por_tipo', to='App_SGC.customtipopatrimonio', verbose_name='Tipo patrimônio *')),
            ],
            options={
                'db_table': 'patrimonio',
                'managed': True,
            },
        ),
    ]
