# Generated by Django 5.0.3 on 2024-07-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0002_custommudanca_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommudanca',
            name='Teste',
        ),
    ]
