# Generated by Django 4.2.13 on 2024-08-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0002_alter_banco_options_alter_banco_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='n_condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *'),
            preserve_default=False,
        ),
    ]
