# Generated by Django 5.0.4 on 2024-06-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0002_custommorador_parentesco_condomino'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcolaborador',
            name='n_condominio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custommorador',
            name='n_condominio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='numero_condominio', to='App_SGC.customcondomino', verbose_name='Número do Condomínio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customcondomino',
            name='n_condominio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio'),
        ),
        migrations.AlterField(
            model_name='custommorador',
            name='cpf_condomino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moradores_por_cpf', to='App_SGC.customcondomino', verbose_name='CPF Condômino *'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='n_condominio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio'),
        ),
    ]
