# Generated by Django 5.0.3 on 2024-07-02 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0002_custombloco_n_condominio_customunidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customunidade',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *'),
        ),
    ]
