# Generated by Django 5.0.4 on 2024-04-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0002_remove_customcondomino_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customcondomino',
            old_name='Condominio_numero',
            new_name='condominio_numero',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='condominio_numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf_usuario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nivel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
