# Generated by Django 4.2.13 on 2024-08-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0002_alter_customplano_conta_nivel_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customconta_receber',
            name='nivel_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivel_4_por_conta_receber', to='App_SGC.customplano_conta', verbose_name='Receber Nível 4 *'),
        ),
    ]
