# Generated by Django 4.2.13 on 2024-08-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0002_customcorrespondencia_customespacoadm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='valor_recebido',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor recebido *'),
        ),
    ]
