# Generated by Django 5.0.4 on 2024-04-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='condominio_numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nivel',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
