# Generated by Django 5.0.3 on 2024-07-02 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0003_alter_customunidade_n_condominio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customunidade',
            options={'managed': True},
        ),
    ]
