# Generated by Django 5.0.3 on 2024-08-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0003_customconta_pagar_valor_conta_paga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customconta_receber',
            old_name='valor_conta_recebimento',
            new_name='valor_conta_recebido',
        ),
    ]
