# Generated by Django 4.2.13 on 2024-08-08 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0003_alter_customconta_receber_nivel_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceiroEstrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='App_SGC.financeiroestrutura', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Estrutura do Financeiro',
                'verbose_name_plural': 'Estruturas do Financeiro',
                'db_table': 'financeiro_estrutura',
                'ordering': ['nome'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Nº Documento')),
                ('tipo_documento', models.CharField(choices=[('NF', 'Nota Fiscal'), ('Recibo', 'Recibo'), ('Outros', 'Outros')], max_length=10, verbose_name='Tipo de Documento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='App_SGC.financeiroestrutura', verbose_name='Categoria')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'db_table': 'receita',
                'ordering': ['data_vencimento'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='customconta_receber',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customconta_receber',
            name='n_condominio',
        ),
        migrations.RemoveField(
            model_name='customconta_receber',
            name='nivel_1',
        ),
        migrations.RemoveField(
            model_name='customconta_receber',
            name='nivel_2',
        ),
        migrations.RemoveField(
            model_name='customconta_receber',
            name='nivel_3',
        ),
        migrations.RemoveField(
            model_name='customconta_receber',
            name='nivel_4',
        ),
        migrations.AlterUniqueTogether(
            name='customplano_conta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customplano_conta',
            name='n_condominio',
        ),
        migrations.DeleteModel(
            name='CustomConta_Pagar',
        ),
        migrations.DeleteModel(
            name='CustomConta_Receber',
        ),
        migrations.DeleteModel(
            name='CustomPlano_Conta',
        ),
    ]
