# Generated by Django 4.2.13 on 2024-08-14 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0003_receita_valor_recebido'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomConta_Pagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField(default=datetime.date.today, verbose_name='Data vencimento *')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data pagamento *')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Nº documento *')),
                ('tipo_documento', models.CharField(choices=[('NF', 'NF'), ('Recibo', 'Recibo'), ('outros', 'Outros')], default='NF', max_length=6, verbose_name='Tipo do Documento')),
                ('descricao', models.CharField(blank=True, max_length=60, null=True, verbose_name='Dsc *')),
                ('valor', models.IntegerField(verbose_name='Valor *')),
                ('valor_recebido', models.IntegerField(blank=True, null=True, verbose_name='Valor recebido *')),
                ('documento_contas_pagar', models.FileField(upload_to='documentos_ocorrencias/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to='App_SGC.financeiroestrutura', verbose_name='Categoria')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
            ],
            options={
                'db_table': 'conta_pagar',
                'ordering': ['data_vencimento', 'tipo_documento', 'categoria'],
                'managed': True,
                'unique_together': {('data_pagamento', 'numero_documento')},
            },
        ),
    ]
