# Generated by Django 4.2.13 on 2024-06-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0003_customcolaborador_n_condominio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcondomino',
            name='telefone_condomino',
            field=models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='Telefone'),
        ),
    ]
