# Generated by Django 5.0.3 on 2024-07-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0003_remove_custommudanca_teste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custommudanca',
            old_name='cpf_condomino',
            new_name='cpf_condomino_id',
        ),
    ]
