# Generated by Django 5.0.4 on 2024-04-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0003_rename_condominio_numero_customcondomino_condominio_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf_usuario',
            field=models.IntegerField(max_length=11),
        ),
    ]
