# Generated by Django 4.2.13 on 2024-08-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0004_financeiroestrutura_receita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiroestrutura',
            name='descricao',
        ),
    ]
