# Generated by Django 5.0.3 on 2024-08-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0004_rename_valor_conta_recebimento_customconta_receber_valor_conta_recebido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompatrimonio',
            name='data_baixa_patrimonio',
            field=models.DateField(blank=True, null=True, verbose_name='Data baixa *'),
        ),
    ]
