# Generated by Django 5.0.4 on 2024-04-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0004_alter_customuser_cpf_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf_usuario',
            field=models.IntegerField(),
        ),
    ]
