# Generated by Django 5.0.3 on 2024-07-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0004_rename_cpf_condomino_custommudanca_cpf_condomino_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcondomino',
            name='apartamento',
        ),
        migrations.RemoveField(
            model_name='customcondomino',
            name='bloco',
        ),
    ]
