# Generated by Django 4.2.13 on 2024-06-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0004_alter_customcondomino_telefone_condomino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommorador',
            name='cpf_morador',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF Morador *'),
        ),
    ]
