# Generated by Django 4.2.13 on 2024-08-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0004_customconta_pagar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomConta_Pagar',
            new_name='Despesas',
        ),
    ]
