# Generated by Django 5.0.3 on 2024-07-03 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0004_alter_customunidade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customunidade',
            options={'managed': True, 'ordering': ['bloco_id__bloco', 'unidade']},
        ),
    ]
