# Generated by Django 4.2.13 on 2024-08-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0005_remove_financeiroestrutura_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiroestrutura',
            options={'managed': True, 'verbose_name': 'Estrutura do Financeiro', 'verbose_name_plural': 'Estruturas do Financeiro'},
        ),
    ]
