# Generated by Django 5.0.3 on 2024-07-15 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0005_remove_customcondomino_apartamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nivel',
        ),
    ]
