# Generated by Django 4.2.13 on 2024-06-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0005_alter_custommorador_cpf_morador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcondomino',
            name='cpf_condomino',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF Condômino *'),
        ),
    ]
