# Generated by Django 5.0.3 on 2024-07-03 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0005_alter_customunidade_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombloco',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *'),
        ),
    ]
