# Generated by Django 5.0.3 on 2024-08-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0005_alter_custompatrimonio_data_baixa_patrimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompatrimonio',
            name='valor_patrimonio',
            field=models.IntegerField(default=0, verbose_name='Valor do patrimônio *'),
        ),
    ]
