# Generated by Django 5.0.4 on 2024-04-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0005_alter_customuser_cpf_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcondomino',
            name='cpf_condomino',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='CPF Condômino *'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpf_usuario',
            field=models.BigIntegerField(),
        ),
    ]
