# Generated by Django 4.2.13 on 2024-08-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0005_rename_customconta_pagar_despesas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesas',
            old_name='documento_contas_pagar',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='despesas',
            old_name='valor_recebido',
            new_name='valor_pago',
        ),
    ]
