# Generated by Django 5.0.3 on 2024-07-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0006_alter_custombloco_n_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcondominio',
            name='n_condominio',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Número do Condomínio *'),
        ),
    ]
