# Generated by Django 4.2.13 on 2024-06-28 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0006_alter_customcondomino_cpf_condomino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommorador',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numero_condominio', to='App_SGC.customcondominio', verbose_name='Número do Condomínio'),
        ),
    ]
