# Generated by Django 4.2.13 on 2024-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0006_rename_documento_contas_pagar_despesas_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor *'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor recebido *'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor recebido *'),
        ),
    ]
