# Generated by Django 5.0.3 on 2024-07-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0006_remove_customuser_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custommudanca',
            old_name='cpf_condomino_id',
            new_name='cpf_condomino',
        ),
    ]
