# Generated by Django 5.0.4 on 2024-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0006_alter_customcondomino_cpf_condomino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
