# Generated by Django 5.0.3 on 2024-08-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0006_custompatrimonio_valor_patrimonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompatrimonio',
            name='valor_patrimonio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor do patrimônio *'),
        ),
    ]
