# Generated by Django 5.0.3 on 2024-07-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0007_rename_cpf_condomino_id_custommudanca_cpf_condomino'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommudanca',
            options={'managed': True, 'ordering': ['bloco_id__bloco', 'data_mudanca']},
        ),
    ]
