# Generated by Django 5.0.3 on 2024-07-03 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0007_alter_customcondominio_n_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcondomino',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='n_condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número do Condomínio'),
        ),
    ]
