# Generated by Django 4.2.13 on 2024-06-06 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0008_alter_customuser_cpf_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf_usuario',
            field=models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14)]),
        ),
    ]
