# Generated by Django 5.0.3 on 2024-07-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0008_alter_customcondomino_n_condominio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGaragem',
            fields=[
                ('garagem_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_garagem', models.CharField(max_length=4, verbose_name='Garagem *')),
                ('bloco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_por_bloco', to='App_SGC.custombloco', verbose_name='Bloco *')),
                ('cpf_condomino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_por_cpf', to='App_SGC.customcondomino', verbose_name='CPF Condômino *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condomínio *')),
            ],
            options={
                'db_table': 'garagem',
                'ordering': ['bloco_id__bloco', 'n_garagem'],
                'managed': True,
            },
        ),
    ]
