# Generated by Django 5.0.3 on 2024-07-16 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0008_alter_custommudanca_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOcorrencia',
            fields=[
                ('ocorrencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_ocorrencia', models.DateField(verbose_name='Data mudança *')),
                ('hora_ocorrencia', models.TimeField(verbose_name='Hora mudança *')),
                ('dsc_ocorrencia', models.CharField(blank=True, max_length=60, null=True, verbose_name='Transportadora *')),
                ('documento_ocorrencia', models.FileField(upload_to='documentos_ocorrencias/')),
                ('cpf_condomino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_por_cpf', to='App_SGC.customcondomino', verbose_name='CPF Condômino *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
            ],
            options={
                'db_table': 'ocorrencia',
                'ordering': ['data_ocorrencia', 'hora_ocorrencia'],
                'managed': True,
            },
        ),
    ]
