# Generated by Django 5.0.3 on 2024-07-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0009_customocorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBeneficio',
            fields=[
                ('beneficio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_beneficio', models.CharField(blank=True, max_length=60, null=True, verbose_name='Transportadora *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
            ],
            options={
                'db_table': 'beneficio',
                'ordering': ['nome_beneficio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomBeneficioRecebido',
            fields=[
                ('beneficio_recebido_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.custombeneficio', verbose_name='Benefício *')),
                ('cpf_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficio_recebido_por_colaborador', to='App_SGC.customcolaborador', verbose_name='CPF Colaborador *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
            ],
            options={
                'db_table': 'beneficio_recebido',
                'ordering': ['cpf_colaborador', 'beneficio_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomPlano_Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_1', models.CharField(max_length=1, verbose_name='Nível 1 *')),
                ('nivel_2', models.CharField(max_length=1, verbose_name='Nível 2 *')),
                ('nivel_3', models.CharField(max_length=1, verbose_name='Nível 3 *')),
                ('nivel_4', models.CharField(max_length=1, verbose_name='Nível 4 *')),
                ('dsc_plano_conta', models.CharField(max_length=100, verbose_name='Dsc *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
            ],
            options={
                'db_table': 'plano_conta',
                'ordering': ['nivel_1', 'nivel_2', 'nivel_3', 'nivel_4'],
                'managed': True,
                'unique_together': {('nivel_1', 'nivel_2', 'nivel_3', 'nivel_4')},
            },
        ),
        migrations.CreateModel(
            name='CustomConta_Receber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conta_receber', models.DateField(verbose_name='Data vencimento *')),
                ('n_documento_conta_receber', models.CharField(max_length=20, verbose_name='Nº documento *')),
                ('tipo_documento_conta_receber', models.CharField(choices=[('NF', 'NF'), ('Recibo', 'Recibo'), ('outros', 'Outros')], default='NF', max_length=6, verbose_name='Tipo do Documento')),
                ('dsc_conta_receber', models.CharField(max_length=60, verbose_name='Dsc *')),
                ('valor_conta_receber', models.IntegerField(verbose_name='Valor *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
                ('nivel_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_1_por_conta_receber', to='App_SGC.customplano_conta', verbose_name='Receber Nível 1 *')),
                ('nivel_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_2_por_conta_receber', to='App_SGC.customplano_conta', verbose_name='Receber Nível 2 *')),
                ('nivel_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_3_por_conta_receber', to='App_SGC.customplano_conta', verbose_name='Receber Nível 3 *')),
                ('nivel_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_4_por_conta_receber', to='App_SGC.customplano_conta', verbose_name='Receber Nível 4 *')),
            ],
            options={
                'db_table': 'conta_receber',
                'ordering': ['data_conta_receber', 'tipo_documento_conta_receber', 'nivel_1', 'nivel_2', 'nivel_3', 'nivel_4'],
                'managed': True,
                'unique_together': {('data_conta_receber', 'n_documento_conta_receber')},
            },
        ),
        migrations.CreateModel(
            name='CustomConta_Pagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conta_pagar', models.DateField(verbose_name='Data vencimento *')),
                ('n_documento_conta_pagar', models.CharField(max_length=20, verbose_name='Nº documento *')),
                ('tipo_documento_conta_pagar', models.CharField(choices=[('NF', 'NF'), ('Recibo', 'Recibo'), ('outros', 'Outros')], default='NF', max_length=6, verbose_name='Tipo do Documento')),
                ('dsc_conta_pagar', models.CharField(max_length=60, verbose_name='Dsc *')),
                ('valor_conta_pagar', models.IntegerField(verbose_name='Valor *')),
                ('n_condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_SGC.customcondominio', verbose_name='Número Condominio *')),
                ('nivel_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_1_por_conta_pagar', to='App_SGC.customplano_conta', verbose_name='Pagar Nível 1 *')),
                ('nivel_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_2_por_conta_pagar', to='App_SGC.customplano_conta', verbose_name='Pagar Nível 2 *')),
                ('nivel_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_3_por_conta_pagar', to='App_SGC.customplano_conta', verbose_name='Pagar Nível 3 *')),
                ('nivel_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel_4_por_conta_pagar', to='App_SGC.customplano_conta', verbose_name='Pagar Nível 4 *')),
            ],
            options={
                'db_table': 'conta_pagar',
                'ordering': ['data_conta_pagar', 'tipo_documento_conta_pagar', 'nivel_1', 'nivel_2', 'nivel_3', 'nivel_4'],
                'managed': True,
                'unique_together': {('data_conta_pagar', 'n_documento_conta_pagar')},
            },
        ),
    ]
