# Generated by Django 4.2.13 on 2024-06-06 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0009_alter_customuser_cpf_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf_usuario',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
