# Generated by Django 5.0.3 on 2024-07-26 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0010_custombeneficio_custombeneficiorecebido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customconta_pagar',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data pagamento *'),
        ),
        migrations.AddField(
            model_name='customconta_receber',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data recebimento *'),
        ),
        migrations.AlterField(
            model_name='customconta_pagar',
            name='data_conta_pagar',
            field=models.DateField(default=datetime.date.today, verbose_name='Data vencimento *'),
        ),
    ]
