# Generated by Django 5.0.3 on 2024-07-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0011_customconta_pagar_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcolaborador',
            options={'managed': True, 'ordering': ['nome_colaborador']},
        ),
        migrations.AlterModelOptions(
            name='customcondominio',
            options={'managed': True, 'ordering': ['nome_condominio']},
        ),
        migrations.AlterModelOptions(
            name='customcondomino',
            options={'managed': True, 'ordering': ['nome_condomino']},
        ),
        migrations.AlterModelOptions(
            name='custommorador',
            options={'managed': True, 'ordering': ['nome_morador']},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': True, 'ordering': ['username']},
        ),
        migrations.AlterModelOptions(
            name='customveiculo',
            options={'managed': True, 'ordering': ['cpf_condomino']},
        ),
        migrations.AlterUniqueTogether(
            name='custombeneficiorecebido',
            unique_together={('beneficio_id', 'cpf_colaborador', 'n_condominio')},
        ),
        migrations.AlterModelTable(
            name='custommorador',
            table='morador',
        ),
    ]
