# Generated by Django 5.0.3 on 2024-07-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0012_alter_customcolaborador_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='custommorador',
            unique_together={('cpf_condomino', 'cpf_morador')},
        ),
    ]
