# Generated by Django 5.0.3 on 2024-07-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0013_alter_custommorador_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommorador',
            name='parentesco_condomino',
            field=models.CharField(choices=[('esposo', 'Esposo(a)'), ('filho', 'Filho(a)'), ('pai', 'Pai'), ('mae', 'Mãe'), ('locatario', 'Locatário'), ('outros', 'Outros')], default='outros', max_length=11, verbose_name='Parentesco'),
        ),
    ]
