# Generated by Django 5.0.3 on 2024-07-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_SGC', '0014_alter_custommorador_parentesco_condomino'),
    ]

    operations = [
        migrations.AddField(
            model_name='customconta_pagar',
            name='documento_contas_pagar',
            field=models.FileField(default=0, upload_to='documentos_ocorrencias/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customconta_pagar',
            name='dsc_conta_pagar',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Dsc *'),
        ),
        migrations.AlterField(
            model_name='customconta_receber',
            name='dsc_conta_receber',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Dsc *'),
        ),
    ]
